volumes:
  minecraft:

services:
  minecraft-server:
    build:
      context: .
      args:
        - SCRIPTCRAFT_REPO_OWNER=softwaremaverick
        - SCRIPTCRAFT_VERSION=3.2.1.2
        - MINECRAFT_VERSION=1.12.2
        - JAVA_VERSION=8
    environment:
      - MINECRAFT_VERSION=1.12.2

    volumes:
      - ./scripts:/minecraft/scriptcraft/plugins/myworld
      - minecraft:/minecraft

    ports:
      - "25565:25565"